//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingRoomTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingRoomEntry
    {
        public int id { get; set; }
        public Nullable<int> teamId { get; set; }
        public Nullable<int> numberOfParticipants { get; set; }
        public Nullable<double> temperature { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> occupiedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual Team Team { get; set; }
    }
}
